--Создаем схему и назначаем владельца
create schema if not exists tinder authorization admin;

--Создаем таблицу
create table if not exists tinder.tinder_users (
  user_id       bigint primary key,
  sex           varchar,
  name          varchar,
  story         text,
  looking_for   varchar
);

create table if not exists tinder.user_matches (
  matches_id    bigint generated by default as identity primary key,
  user_id       bigint foreign key,
  liked_id      bigint foreign key
);